#define	I2C_ISR_RX_UNDER_Pos                                (0)
#define	I2C_ISR_RX_UNDER                                    (0x01U << I2C_ISR_RX_UNDER_Pos)
#define	I2C_ISR_RX_OVER_Pos                                 (1)
#define	I2C_ISR_RX_OVER                                     (0x01U << I2C_ISR_RX_OVER_Pos)
#define	I2C_ISR_RX_FULL_Pos                                 (2)
#define	I2C_ISR_RX_FULL                                     (0x01U << I2C_ISR_RX_FULL_Pos)
#define	I2C_ISR_TX_OVER_Pos                                 (3)
#define	I2C_ISR_TX_OVER                                     (0x01U << I2C_ISR_TX_OVER_Pos)
#define	I2C_ISR_TX_EMPTY_Pos                                (4)
#define	I2C_ISR_TX_EMPTY                                    (0x01U << I2C_ISR_TX_EMPTY_Pos)
#define	I2C_ISR_RX_REQ_Pos                                  (5)
#define	I2C_ISR_RX_REQ                                      (0x01U << I2C_ISR_RX_REQ_Pos)
#define	I2C_ISR_TX_ABRT_Pos                                 (6)
#define	I2C_ISR_TX_ABRT                                     (0x01U << I2C_ISR_TX_ABRT_Pos)
#define	I2C_ISR_RX_DONE_Pos                                 (7)
#define	I2C_ISR_RX_DONE                                     (0x01U << I2C_ISR_RX_DONE_Pos)
#define	I2C_ISR_ACTIV_Pos                                   (8)
#define	I2C_ISR_ACTIV                                       (0x01U << I2C_ISR_ACTIV_Pos)
#define	I2C_ISR_STOP_Pos                                    (9)
#define	I2C_ISR_STOP                                        (0x01U << I2C_ISR_STOP_Pos)
#define	I2C_ISR_START_Pos                                   (10)
#define	I2C_ISR_START                                       (0x01U << I2C_ISR_START_Pos)
#define	I2C_ISR_GC_Pos                                      (11)
#define	I2C_ISR_GC                                          (0x01U << I2C_ISR_GC_Pos)
#define	I2C_ISR_RESTART_Pos                                 (12)
#define	I2C_ISR_RESTART                                     (0x01U << I2C_ISR_RESTART_Pos)
#define	I2C_ISR_HOLD_Pos                                    (13)
#define	I2C_ISR_HOLD                                        (0x01U << I2C_ISR_HOLD_Pos)
