#define	ADC_CHSR_CH0_Pos                                    (0)
#define	ADC_CHSR_CH0                                        (0x01U << ADC_CHSR_CH0_Pos)
#define	ADC_CHSR_CH1_Pos                                    (1)
#define	ADC_CHSR_CH1                                        (0x01U << ADC_CHSR_CH1_Pos)
#define	ADC_CHSR_CH2_Pos                                    (2)
#define	ADC_CHSR_CH2                                        (0x01U << ADC_CHSR_CH2_Pos)
#define	ADC_CHSR_CH3_Pos                                    (3)
#define	ADC_CHSR_CH3                                        (0x01U << ADC_CHSR_CH3_Pos)
#define	ADC_CHSR_CH4_Pos                                    (4)
#define	ADC_CHSR_CH4                                        (0x01U << ADC_CHSR_CH4_Pos)
#define	ADC_CHSR_CH5_Pos                                    (5)
#define	ADC_CHSR_CH5                                        (0x01U << ADC_CHSR_CH5_Pos)
#define	ADC_CHSR_CH6_Pos                                    (6)
#define	ADC_CHSR_CH6                                        (0x01U << ADC_CHSR_CH6_Pos)
#define	ADC_CHSR_CH7_Pos                                    (7)
#define	ADC_CHSR_CH7                                        (0x01U << ADC_CHSR_CH7_Pos)
#define	ADC_CHSR_CHTV_Pos                                   (8)
#define	ADC_CHSR_CHTV                                       (0x01U << ADC_CHSR_CHTV_Pos)
