#define	ADC_SR_ADIF_Pos                                     (0)
#define	ADC_SR_ADIF                                         (0x01U << ADC_SR_ADIF_Pos)
#define	ADC_SR_ADWIF_Pos                                    (1)
#define	ADC_SR_ADWIF                                        (0x01U << ADC_SR_ADWIF_Pos)
#define	ADC_SR_BUSY_Pos                                     (2)
#define	ADC_SR_BUSY                                         (0x01U << ADC_SR_BUSY_Pos)
#define	ADC_SR_CH_Pos                                       (4)
#define	ADC_SR_CH                                           (0x0FU << ADC_SR_CH_Pos)
#define	ADC_SR_VALID_Pos                                    (8)
#define	ADC_SR_VALID                                        (0x01FFU << ADC_SR_VALID_Pos)
#define	ADC_SR_OVERRUN_Pos                                  (20)
#define	ADC_SR_OVERRUN                                      (0x01FFU << ADC_SR_OVERRUN_Pos)
