#define	DMA_ISR_GIF1_Pos                                    (0)
#define	DMA_ISR_GIF1                                        (0x01U << DMA_ISR_GIF1_Pos)
#define	DMA_ISR_TCIF1_Pos                                   (1)
#define	DMA_ISR_TCIF1                                       (0x01U << DMA_ISR_TCIF1_Pos)
#define	DMA_ISR_HTIF1_Pos                                   (2)
#define	DMA_ISR_HTIF1                                       (0x01U << DMA_ISR_HTIF1_Pos)
#define	DMA_ISR_TEIF1_Pos                                   (3)
#define	DMA_ISR_TEIF1                                       (0x01U << DMA_ISR_TEIF1_Pos)
#define	DMA_ISR_GIF2_Pos                                    (4)
#define	DMA_ISR_GIF2                                        (0x01U << DMA_ISR_GIF2_Pos)
#define	DMA_ISR_TCIF2_Pos                                   (5)
#define	DMA_ISR_TCIF2                                       (0x01U << DMA_ISR_TCIF2_Pos)
#define	DMA_ISR_HTIF2_Pos                                   (6)
#define	DMA_ISR_HTIF2                                       (0x01U << DMA_ISR_HTIF2_Pos)
#define	DMA_ISR_TEIF2_Pos                                   (7)
#define	DMA_ISR_TEIF2                                       (0x01U << DMA_ISR_TEIF2_Pos)
#define	DMA_ISR_GIF3_Pos                                    (8)
#define	DMA_ISR_GIF3                                        (0x01U << DMA_ISR_GIF3_Pos)
#define	DMA_ISR_TCIF3_Pos                                   (9)
#define	DMA_ISR_TCIF3                                       (0x01U << DMA_ISR_TCIF3_Pos)
#define	DMA_ISR_HTIF3_Pos                                   (10)
#define	DMA_ISR_HTIF3                                       (0x01U << DMA_ISR_HTIF3_Pos)
#define	DMA_ISR_TEIF3_Pos                                   (11)
#define	DMA_ISR_TEIF3                                       (0x01U << DMA_ISR_TEIF3_Pos)
#define	DMA_ISR_GIF4_Pos                                    (12)
#define	DMA_ISR_GIF4                                        (0x01U << DMA_ISR_GIF4_Pos)
#define	DMA_ISR_TCIF4_Pos                                   (13)
#define	DMA_ISR_TCIF4                                       (0x01U << DMA_ISR_TCIF4_Pos)
#define	DMA_ISR_HTIF4_Pos                                   (14)
#define	DMA_ISR_HTIF4                                       (0x01U << DMA_ISR_HTIF4_Pos)
#define	DMA_ISR_TEIF4_Pos                                   (15)
#define	DMA_ISR_TEIF4                                       (0x01U << DMA_ISR_TEIF4_Pos)
#define	DMA_ISR_GIF5_Pos                                    (16)
#define	DMA_ISR_GIF5                                        (0x01U << DMA_ISR_GIF5_Pos)
#define	DMA_ISR_TCIF5_Pos                                   (17)
#define	DMA_ISR_TCIF5                                       (0x01U << DMA_ISR_TCIF5_Pos)
#define	DMA_ISR_HTIF5_Pos                                   (18)
#define	DMA_ISR_HTIF5                                       (0x01U << DMA_ISR_HTIF5_Pos)
#define	DMA_ISR_TEIF5_Pos                                   (19)
#define	DMA_ISR_TEIF5                                       (0x01U << DMA_ISR_TEIF5_Pos)
#define	DMA_ISR_GIF6_Pos                                    (20)
#define	DMA_ISR_GIF6                                        (0x01U << DMA_ISR_GIF6_Pos)
#define	DMA_ISR_TCIF6_Pos                                   (21)
#define	DMA_ISR_TCIF6                                       (0x01U << DMA_ISR_TCIF6_Pos)
#define	DMA_ISR_HTIF6_Pos                                   (22)
#define	DMA_ISR_HTIF6                                       (0x01U << DMA_ISR_HTIF6_Pos)
#define	DMA_ISR_TEIF6_Pos                                   (23)
#define	DMA_ISR_TEIF6                                       (0x01U << DMA_ISR_TEIF6_Pos)
#define	DMA_ISR_GIF7_Pos                                    (24)
#define	DMA_ISR_GIF7                                        (0x01U << DMA_ISR_GIF7_Pos)
#define	DMA_ISR_TCIF7_Pos                                   (25)
#define	DMA_ISR_TCIF7                                       (0x01U << DMA_ISR_TCIF7_Pos)
#define	DMA_ISR_HTIF7_Pos                                   (26)
#define	DMA_ISR_HTIF7                                       (0x01U << DMA_ISR_HTIF7_Pos)
#define	DMA_ISR_TEIF7_Pos                                   (27)
#define	DMA_ISR_TEIF7                                       (0x01U << DMA_ISR_TEIF7_Pos)
