#define	TIM_BDTR_DTG_Pos                                    (7)
#define	TIM_BDTR_DTG                                        (0x0FFU << TIM_BDTR_DTG_Pos)
#define	TIM_BDTR_LOCK_Pos                                   (9)
#define	TIM_BDTR_LOCK                                       (0x03U << TIM_BDTR_LOCK_Pos)
#define	TIM_BDTR_OSSI_Pos                                   (10)
#define	TIM_BDTR_OSSI                                       (0x01U << TIM_BDTR_OSSI_Pos)
#define	TIM_BDTR_OSSR_Pos                                   (11)
#define	TIM_BDTR_OSSR                                       (0x01U << TIM_BDTR_OSSR_Pos)
#define	TIM_BDTR_BKE_Pos                                    (12)
#define	TIM_BDTR_BKE                                        (0x01U << TIM_BDTR_BKE_Pos)
#define	TIM_BDTR_BKP_Pos                                    (13)
#define	TIM_BDTR_BKP                                        (0x01U << TIM_BDTR_BKP_Pos)
#define	TIM_BDTR_AOE_Pos                                    (14)
#define	TIM_BDTR_AOE                                        (0x01U << TIM_BDTR_AOE_Pos)
#define	TIM_BDTR_MOE_Pos                                    (15)
#define	TIM_BDTR_MOE                                        (0x01U << TIM_BDTR_MOE_Pos)
