#define	TIM_CCMR1_CC1S_Pos                                  (0)
#define	TIM_CCMR1_CC1S                                      (0x03U << TIM_CCMR1_CC1S_Pos)
#define	TIM_CCMR1_IC1PSC_Pos                                (2)
#define	TIM_CCMR1_IC1PSC                                    (0x03U << TIM_CCMR1_IC1PSC_Pos)
#define	TIM_CCMR1_IC1F_Pos                                  (4)
#define	TIM_CCMR1_IC1F                                      (0x0FU << TIM_CCMR1_IC1F_Pos)
#define	TIM_CCMR1_CC2S_Pos                                  (8)
#define	TIM_CCMR1_CC2S                                      (0x03U << TIM_CCMR1_CC2S_Pos)
#define	TIM_CCMR1_IC2PSC_Pos                                (10)
#define	TIM_CCMR1_IC2PSC                                    (0x03U << TIM_CCMR1_IC2PSC_Pos)
#define	TIM_CCMR1_IC2F_Pos                                  (12)
#define	TIM_CCMR1_IC2F                                      (0x0FU << TIM_CCMR1_IC2F_Pos)
#define	TIM_CCMR1_CC1S_Pos                                  (16)
#define	TIM_CCMR1_CC1S                                      (0x03U << TIM_CCMR1_CC1S_Pos)
#define	TIM_CCMR1_OC1FE_Pos                                 (18)
#define	TIM_CCMR1_OC1FE                                     (0x01U << TIM_CCMR1_OC1FE_Pos)
#define	TIM_CCMR1_OC1PE_Pos                                 (19)
#define	TIM_CCMR1_OC1PE                                     (0x01U << TIM_CCMR1_OC1PE_Pos)
#define	TIM_CCMR1_OC1M_Pos                                  (20)
#define	TIM_CCMR1_OC1M                                      (0x07U << TIM_CCMR1_OC1M_Pos)
#define	TIM_CCMR1_OC1CE_Pos                                 (23)
#define	TIM_CCMR1_OC1CE                                     (0x01U << TIM_CCMR1_OC1CE_Pos)
#define	TIM_CCMR1_CC2S_Pos                                  (24)
#define	TIM_CCMR1_CC2S                                      (0x03U << TIM_CCMR1_CC2S_Pos)
#define	TIM_CCMR1_OC2FE_Pos                                 (26)
#define	TIM_CCMR1_OC2FE                                     (0x01U << TIM_CCMR1_OC2FE_Pos)
#define	TIM_CCMR1_OC2PE_Pos                                 (27)
#define	TIM_CCMR1_OC2PE                                     (0x01U << TIM_CCMR1_OC2PE_Pos)
#define	TIM_CCMR1_OC2M_Pos                                  (28)
#define	TIM_CCMR1_OC2M                                      (0x07U << TIM_CCMR1_OC2M_Pos)
#define	TIM_CCMR1_OC2CE_Pos                                 (31)
#define	TIM_CCMR1_OC2CE                                     (0x01U << TIM_CCMR1_OC2CE_Pos)
