#define	TIM_CCMR2_CC3S_Pos                                  (0)
#define	TIM_CCMR2_CC3S                                      (0x03U << TIM_CCMR2_CC3S_Pos)
#define	TIM_CCMR2_IC3PSC_Pos                                (2)
#define	TIM_CCMR2_IC3PSC                                    (0x03U << TIM_CCMR2_IC3PSC_Pos)
#define	TIM_CCMR2_IC3F_Pos                                  (4)
#define	TIM_CCMR2_IC3F                                      (0x0FU << TIM_CCMR2_IC3F_Pos)
#define	TIM_CCMR2_CC4S_Pos                                  (8)
#define	TIM_CCMR2_CC4S                                      (0x03U << TIM_CCMR2_CC4S_Pos)
#define	TIM_CCMR2_IC4PSC_Pos                                (10)
#define	TIM_CCMR2_IC4PSC                                    (0x03U << TIM_CCMR2_IC4PSC_Pos)
#define	TIM_CCMR2_IC4F_Pos                                  (12)
#define	TIM_CCMR2_IC4F                                      (0x0FU << TIM_CCMR2_IC4F_Pos)
#define	TIM_CCMR2_CC3S_Pos                                  (16)
#define	TIM_CCMR2_CC3S                                      (0x03U << TIM_CCMR2_CC3S_Pos)
#define	TIM_CCMR2_OC3FE_Pos                                 (18)
#define	TIM_CCMR2_OC3FE                                     (0x01U << TIM_CCMR2_OC3FE_Pos)
#define	TIM_CCMR2_OC3PE_Pos                                 (19)
#define	TIM_CCMR2_OC3PE                                     (0x01U << TIM_CCMR2_OC3PE_Pos)
#define	TIM_CCMR2_OC3M_Pos                                  (20)
#define	TIM_CCMR2_OC3M                                      (0x07U << TIM_CCMR2_OC3M_Pos)
#define	TIM_CCMR2_OC3CE_Pos                                 (23)
#define	TIM_CCMR2_OC3CE                                     (0x01U << TIM_CCMR2_OC3CE_Pos)
#define	TIM_CCMR2_CC4S_Pos                                  (24)
#define	TIM_CCMR2_CC4S                                      (0x03U << TIM_CCMR2_CC4S_Pos)
#define	TIM_CCMR2_OC4FE_Pos                                 (26)
#define	TIM_CCMR2_OC4FE                                     (0x01U << TIM_CCMR2_OC4FE_Pos)
#define	TIM_CCMR2_OC4PE_Pos                                 (27)
#define	TIM_CCMR2_OC4PE                                     (0x01U << TIM_CCMR2_OC4PE_Pos)
#define	TIM_CCMR2_OC4M_Pos                                  (28)
#define	TIM_CCMR2_OC4M                                      (0x07U << TIM_CCMR2_OC4M_Pos)
#define	TIM_CCMR2_OC4CE_Pos                                 (31)
#define	TIM_CCMR2_OC4CE                                     (0x01U << TIM_CCMR2_OC4CE_Pos)
