#define	TIM_CR1_CEN_Pos                                     (0)
#define	TIM_CR1_CEN                                         (0x01U << TIM_CR1_CEN_Pos)
#define	TIM_CR1_UDIS_Pos                                    (1)
#define	TIM_CR1_UDIS                                        (0x01U << TIM_CR1_UDIS_Pos)
#define	TIM_CR1_URS_Pos                                     (2)
#define	TIM_CR1_URS                                         (0x01U << TIM_CR1_URS_Pos)
#define	TIM_CR1_OPM_Pos                                     (3)
#define	TIM_CR1_OPM                                         (0x01U << TIM_CR1_OPM_Pos)
#define	TIM_CR1_DIR_Pos                                     (4)
#define	TIM_CR1_DIR                                         (0x01U << TIM_CR1_DIR_Pos)
#define	TIM_CR1_CMS_Pos                                     (6)
#define	TIM_CR1_CMS                                         (0x03U << TIM_CR1_CMS_Pos)
#define	TIM_CR1_ARPEN_Pos                                   (7)
#define	TIM_CR1_ARPEN                                       (0x01U << TIM_CR1_ARPEN_Pos)
#define	TIM_CR1_CKD_Pos                                     (9)
#define	TIM_CR1_CKD                                         (0x03U << TIM_CR1_CKD_Pos)
