#define	TIM_DIER_UI_Pos                                     (0)
#define	TIM_DIER_UI                                         (0x01U << TIM_DIER_UI_Pos)
#define	TIM_DIER_CC1I_Pos                                   (1)
#define	TIM_DIER_CC1I                                       (0x01U << TIM_DIER_CC1I_Pos)
#define	TIM_DIER_CC2I_Pos                                   (2)
#define	TIM_DIER_CC2I                                       (0x01U << TIM_DIER_CC2I_Pos)
#define	TIM_DIER_CC3I_Pos                                   (3)
#define	TIM_DIER_CC3I                                       (0x01U << TIM_DIER_CC3I_Pos)
#define	TIM_DIER_CC4I_Pos                                   (4)
#define	TIM_DIER_CC4I                                       (0x01U << TIM_DIER_CC4I_Pos)
#define	TIM_DIER_COMI_Pos                                   (5)
#define	TIM_DIER_COMI                                       (0x01U << TIM_DIER_COMI_Pos)
#define	TIM_DIER_TI_Pos                                     (6)
#define	TIM_DIER_TI                                         (0x01U << TIM_DIER_TI_Pos)
#define	TIM_DIER_BI_Pos                                     (7)
#define	TIM_DIER_BI                                         (0x01U << TIM_DIER_BI_Pos)
#define	TIM_DIER_UD_Pos                                     (8)
#define	TIM_DIER_UD                                         (0x01U << TIM_DIER_UD_Pos)
#define	TIM_DIER_CC1D_Pos                                   (9)
#define	TIM_DIER_CC1D                                       (0x01U << TIM_DIER_CC1D_Pos)
#define	TIM_DIER_CC2D_Pos                                   (10)
#define	TIM_DIER_CC2D                                       (0x01U << TIM_DIER_CC2D_Pos)
#define	TIM_DIER_CC3D_Pos                                   (11)
#define	TIM_DIER_CC3D                                       (0x01U << TIM_DIER_CC3D_Pos)
#define	TIM_DIER_CC4D_Pos                                   (12)
#define	TIM_DIER_CC4D                                       (0x01U << TIM_DIER_CC4D_Pos)
#define	TIM_DIER_COMD_Pos                                   (13)
#define	TIM_DIER_COMD                                       (0x01U << TIM_DIER_COMD_Pos)
#define	TIM_DIER_TD_Pos                                     (14)
#define	TIM_DIER_TD                                         (0x01U << TIM_DIER_TD_Pos)
