#define	TIM_SMCR_SMS_Pos                                    (2)
#define	TIM_SMCR_SMS                                        (0x07U << TIM_SMCR_SMS_Pos)
#define	TIM_SMCR_TS_Pos                                     (6)
#define	TIM_SMCR_TS                                         (0x07U << TIM_SMCR_TS_Pos)
#define	TIM_SMCR_MSM_Pos                                    (7)
#define	TIM_SMCR_MSM                                        (0x01U << TIM_SMCR_MSM_Pos)
#define	TIM_SMCR_ETF_Pos                                    (11)
#define	TIM_SMCR_ETF                                        (0x0FU << TIM_SMCR_ETF_Pos)
#define	TIM_SMCR_ETPS_Pos                                   (13)
#define	TIM_SMCR_ETPS                                       (0x03U << TIM_SMCR_ETPS_Pos)
#define	TIM_SMCR_ECE_Pos                                    (14)
#define	TIM_SMCR_ECE                                        (0x01U << TIM_SMCR_ECE_Pos)
#define	TIM_SMCR_ETP_Pos                                    (15)
#define	TIM_SMCR_ETP                                        (0x01U << TIM_SMCR_ETP_Pos)
