#define	FLASH_OBR_OPTERR_Pos                                (0)
#define	FLASH_OBR_OPTERR                                    (0x01U << FLASH_OBR_OPTERR_Pos)
#define	FLASH_OBR_USER_Pos                                  (6)
#define	FLASH_OBR_USER                                      (0x0FU << FLASH_OBR_USER_Pos)
#define	FLASH_OBR_Data0_Pos                                 (15)
#define	FLASH_OBR_Data0                                     (0x03FU << FLASH_OBR_Data0_Pos)
#define	FLASH_OBR_Data0_Pos                                 (17)
#define	FLASH_OBR_Data0                                     (0x03U << FLASH_OBR_Data0_Pos)
#define	FLASH_OBR_Data1_Pos                                 (25)
#define	FLASH_OBR_Data1                                     (0x0FFU << FLASH_OBR_Data1_Pos)
