#define	AES_CR_EN_Pos                                       (0)
#define	AES_CR_EN                                           (0x01U << AES_CR_EN_Pos)
#define	AES_CR_DATATYPE_Pos                                 (1)
#define	AES_CR_DATATYPE                                     (0x03U << AES_CR_DATATYPE_Pos)
#define	AES_CR_MODE_Pos                                     (3)
#define	AES_CR_MODE                                         (0x03U << AES_CR_MODE_Pos)
#define	AES_CR_CHMOD[1:0]_Pos                               (5)
#define	AES_CR_CHMOD[1:0]                                   (0x03U << AES_CR_CHMOD[1:0]_Pos)
#define	AES_CR_CCFC_Pos                                     (7)
#define	AES_CR_CCFC                                         (0x01U << AES_CR_CCFC_Pos)
#define	AES_CR_ERRC_Pos                                     (8)
#define	AES_CR_ERRC                                         (0x01U << AES_CR_ERRC_Pos)
#define	AES_CR_CCFIE_Pos                                    (9)
#define	AES_CR_CCFIE                                        (0x01U << AES_CR_CCFIE_Pos)
#define	AES_CR_ERRIE_Pos                                    (10)
#define	AES_CR_ERRIE                                        (0x01U << AES_CR_ERRIE_Pos)
#define	AES_CR_DMAINEN_Pos                                  (11)
#define	AES_CR_DMAINEN                                      (0x01U << AES_CR_DMAINEN_Pos)
#define	AES_CR_DMAOUTEN_Pos                                 (12)
#define	AES_CR_DMAOUTEN                                     (0x01U << AES_CR_DMAOUTEN_Pos)
#define	AES_CR_CHMOD[2]_Pos                                 (16)
#define	AES_CR_CHMOD[2]                                     (0x01U << AES_CR_CHMOD[2]_Pos)
#define	AES_CR_KSIZE_Pos                                    (18)
#define	AES_CR_KSIZE                                        (0x03U << AES_CR_KSIZE_Pos)
#define	AES_CR_FBSEL_Pos                                    (20)
#define	AES_CR_FBSEL                                        (0x03U << AES_CR_FBSEL_Pos)
