#define	_ok_RCC_RCC_0_CR-1_HSION_Pos                        (0)
#define	_ok_RCC_RCC_0_CR-1_HSION                            (0x01U << _ok_RCC_RCC_0_CR-1_HSION_Pos)
#define	_ok_RCC_RCC_0_CR-1_HSIRDY_Pos                       (1)
#define	_ok_RCC_RCC_0_CR-1_HSIRDY                           (0x01U << _ok_RCC_RCC_0_CR-1_HSIRDY_Pos)
#define	_ok_RCC_RCC_0_CR-1_HSICAL_Pos                       (9)
#define	_ok_RCC_RCC_0_CR-1_HSICAL                           (0x07FU << _ok_RCC_RCC_0_CR-1_HSICAL_Pos)
#define	_ok_RCC_RCC_0_CR-1_HSE0_Pos                         (16)
#define	_ok_RCC_RCC_0_CR-1_HSE0                             (0x01U << _ok_RCC_RCC_0_CR-1_HSE0_Pos)
#define	_ok_RCC_RCC_0_CR-1_HSERDY_Pos                       (17)
#define	_ok_RCC_RCC_0_CR-1_HSERDY                           (0x01U << _ok_RCC_RCC_0_CR-1_HSERDY_Pos)
#define	_ok_RCC_RCC_0_CR-1_HSE1_Pos                         (18)
#define	_ok_RCC_RCC_0_CR-1_HSE1                             (0x01U << _ok_RCC_RCC_0_CR-1_HSE1_Pos)
#define	_ok_RCC_RCC_0_CR-1_CSSON_Pos                        (19)
#define	_ok_RCC_RCC_0_CR-1_CSSON                            (0x01U << _ok_RCC_RCC_0_CR-1_CSSON_Pos)
#define	_ok_RCC_RCC_0_CR-1_PLLDIV_Pos                       (20)
#define	_ok_RCC_RCC_0_CR-1_PLLDIV                           (0x07U << _ok_RCC_RCC_0_CR-1_PLLDIV_Pos)
#define	_ok_RCC_RCC_0_CR-1_PLLON_Pos                        (24)
#define	_ok_RCC_RCC_0_CR-1_PLLON                            (0x01U << _ok_RCC_RCC_0_CR-1_PLLON_Pos)
#define	_ok_RCC_RCC_0_CR-1_PLLRDY_Pos                       (25)
#define	_ok_RCC_RCC_0_CR-1_PLLRDY                           (0x01U << _ok_RCC_RCC_0_CR-1_PLLRDY_Pos)
#define	_ok_RCC_RCC_0_CR-1_PLLMUL_Pos                       (26)
#define	_ok_RCC_RCC_0_CR-1_PLLMUL                           (0x03FU << _ok_RCC_RCC_0_CR-1_PLLMUL_Pos)
