#define	_ok_RCC_RCC_1_CFGR_SW_Pos                           (0)
#define	_ok_RCC_RCC_1_CFGR_SW                               (0x03U << _ok_RCC_RCC_1_CFGR_SW_Pos)
#define	_ok_RCC_RCC_1_CFGR_SWS_Pos                          (2)
#define	_ok_RCC_RCC_1_CFGR_SWS                              (0x03U << _ok_RCC_RCC_1_CFGR_SWS_Pos)
#define	_ok_RCC_RCC_1_CFGR_HPRE_Pos                         (4)
#define	_ok_RCC_RCC_1_CFGR_HPRE                             (0x0FU << _ok_RCC_RCC_1_CFGR_HPRE_Pos)
#define	_ok_RCC_RCC_1_CFGR_PPRE1_Pos                        (8)
#define	_ok_RCC_RCC_1_CFGR_PPRE1                            (0x07U << _ok_RCC_RCC_1_CFGR_PPRE1_Pos)
#define	_ok_RCC_RCC_1_CFGR_PPRE2_Pos                        (11)
#define	_ok_RCC_RCC_1_CFGR_PPRE2                            (0x07U << _ok_RCC_RCC_1_CFGR_PPRE2_Pos)
#define	_ok_RCC_RCC_1_CFGR_PLLSRC_Pos                       (16)
#define	_ok_RCC_RCC_1_CFGR_PLLSRC                           (0x01U << _ok_RCC_RCC_1_CFGR_PLLSRC_Pos)
#define	_ok_RCC_RCC_1_CFGR_SRCDIV_Pos                       (17)
#define	_ok_RCC_RCC_1_CFGR_SRCDIV                           (0x01U << _ok_RCC_RCC_1_CFGR_SRCDIV_Pos)
#define	_ok_RCC_RCC_1_CFGR_USBPRE_Pos                       (22)
#define	_ok_RCC_RCC_1_CFGR_USBPRE                           (0x03U << _ok_RCC_RCC_1_CFGR_USBPRE_Pos)
#define	_ok_RCC_RCC_1_CFGR_MCO_Pos                          (24)
#define	_ok_RCC_RCC_1_CFGR_MCO                              (0x07U << _ok_RCC_RCC_1_CFGR_MCO_Pos)
