#define	_ok_RCC_RCC_6_APB2ENR_AFIO_Pos                      (0)
#define	_ok_RCC_RCC_6_APB2ENR_AFIO                          (0x01U << _ok_RCC_RCC_6_APB2ENR_AFIO_Pos)
#define	_ok_RCC_RCC_6_APB2ENR_PORTA_Pos                     (2)
#define	_ok_RCC_RCC_6_APB2ENR_PORTA                         (0x01U << _ok_RCC_RCC_6_APB2ENR_PORTA_Pos)
#define	_ok_RCC_RCC_6_APB2ENR_PORTB_Pos                     (3)
#define	_ok_RCC_RCC_6_APB2ENR_PORTB                         (0x01U << _ok_RCC_RCC_6_APB2ENR_PORTB_Pos)
#define	_ok_RCC_RCC_6_APB2ENR_PORTC_Pos                     (4)
#define	_ok_RCC_RCC_6_APB2ENR_PORTC                         (0x01U << _ok_RCC_RCC_6_APB2ENR_PORTC_Pos)
#define	_ok_RCC_RCC_6_APB2ENR_PORTD_Pos                     (5)
#define	_ok_RCC_RCC_6_APB2ENR_PORTD                         (0x01U << _ok_RCC_RCC_6_APB2ENR_PORTD_Pos)
#define	_ok_RCC_RCC_6_APB2ENR_ADC1_Pos                      (9)
#define	_ok_RCC_RCC_6_APB2ENR_ADC1                          (0x01U << _ok_RCC_RCC_6_APB2ENR_ADC1_Pos)
#define	_ok_RCC_RCC_6_APB2ENR_ADC2_Pos                      (10)
#define	_ok_RCC_RCC_6_APB2ENR_ADC2                          (0x01U << _ok_RCC_RCC_6_APB2ENR_ADC2_Pos)
#define	_ok_RCC_RCC_6_APB2ENR_TIM1_Pos                      (11)
#define	_ok_RCC_RCC_6_APB2ENR_TIM1                          (0x01U << _ok_RCC_RCC_6_APB2ENR_TIM1_Pos)
#define	_ok_RCC_RCC_6_APB2ENR_SPI1_Pos                      (12)
#define	_ok_RCC_RCC_6_APB2ENR_SPI1                          (0x01U << _ok_RCC_RCC_6_APB2ENR_SPI1_Pos)
#define	_ok_RCC_RCC_6_APB2ENR_UART1_Pos                     (14)
#define	_ok_RCC_RCC_6_APB2ENR_UART1                         (0x01U << _ok_RCC_RCC_6_APB2ENR_UART1_Pos)
