#define	_ok_RCC_RCC_4_APB1RSTR_TIM2_Pos                     (0)
#define	_ok_RCC_RCC_4_APB1RSTR_TIM2                         (0x01U << _ok_RCC_RCC_4_APB1RSTR_TIM2_Pos)
#define	_ok_RCC_RCC_4_APB1RSTR_TIM3_Pos                     (1)
#define	_ok_RCC_RCC_4_APB1RSTR_TIM3                         (0x01U << _ok_RCC_RCC_4_APB1RSTR_TIM3_Pos)
#define	_ok_RCC_RCC_4_APB1RSTR_TIM4_Pos                     (2)
#define	_ok_RCC_RCC_4_APB1RSTR_TIM4                         (0x01U << _ok_RCC_RCC_4_APB1RSTR_TIM4_Pos)
#define	_ok_RCC_RCC_4_APB1RSTR_WWDG_Pos                     (11)
#define	_ok_RCC_RCC_4_APB1RSTR_WWDG                         (0x01U << _ok_RCC_RCC_4_APB1RSTR_WWDG_Pos)
#define	_ok_RCC_RCC_4_APB1RSTR_SPI2_Pos                     (14)
#define	_ok_RCC_RCC_4_APB1RSTR_SPI2                         (0x01U << _ok_RCC_RCC_4_APB1RSTR_SPI2_Pos)
#define	_ok_RCC_RCC_4_APB1RSTR_UART2_Pos                    (17)
#define	_ok_RCC_RCC_4_APB1RSTR_UART2                        (0x01U << _ok_RCC_RCC_4_APB1RSTR_UART2_Pos)
#define	_ok_RCC_RCC_4_APB1RSTR_UART3_Pos                    (18)
#define	_ok_RCC_RCC_4_APB1RSTR_UART3                        (0x01U << _ok_RCC_RCC_4_APB1RSTR_UART3_Pos)
#define	_ok_RCC_RCC_4_APB1RSTR_I2C1_Pos                     (21)
#define	_ok_RCC_RCC_4_APB1RSTR_I2C1                         (0x01U << _ok_RCC_RCC_4_APB1RSTR_I2C1_Pos)
#define	_ok_RCC_RCC_4_APB1RSTR_I2C2_Pos                     (22)
#define	_ok_RCC_RCC_4_APB1RSTR_I2C2                         (0x01U << _ok_RCC_RCC_4_APB1RSTR_I2C2_Pos)
#define	_ok_RCC_RCC_4_APB1RSTR_USB_Pos                      (23)
#define	_ok_RCC_RCC_4_APB1RSTR_USB                          (0x01U << _ok_RCC_RCC_4_APB1RSTR_USB_Pos)
#define	_ok_RCC_RCC_4_APB1RSTR_CRS_Pos                      (24)
#define	_ok_RCC_RCC_4_APB1RSTR_CRS                          (0x01U << _ok_RCC_RCC_4_APB1RSTR_CRS_Pos)
#define	_ok_RCC_RCC_4_APB1RSTR_CAN_Pos                      (25)
#define	_ok_RCC_RCC_4_APB1RSTR_CAN                          (0x01U << _ok_RCC_RCC_4_APB1RSTR_CAN_Pos)
#define	_ok_RCC_RCC_4_APB1RSTR_BKP_Pos                      (27)
#define	_ok_RCC_RCC_4_APB1RSTR_BKP                          (0x01U << _ok_RCC_RCC_4_APB1RSTR_BKP_Pos)
#define	_ok_RCC_RCC_4_APB1RSTR_PWR_Pos                      (28)
#define	_ok_RCC_RCC_4_APB1RSTR_PWR                          (0x01U << _ok_RCC_RCC_4_APB1RSTR_PWR_Pos)
#define	_ok_RCC_RCC_4_APB1RSTR_DAC_Pos                      (29)
#define	_ok_RCC_RCC_4_APB1RSTR_DAC                          (0x01U << _ok_RCC_RCC_4_APB1RSTR_DAC_Pos)
