#define	CAN_BTR1_TESG1_Pos                                  (0)
#define	CAN_BTR1_TESG1                                      (0x0FU << CAN_BTR1_TESG1_Pos)
#define	CAN_BTR1_TESG2_Pos                                  (4)
#define	CAN_BTR1_TESG2                                      (0x07U << CAN_BTR1_TESG2_Pos)
#define	CAN_BTR1_SAM_Pos                                    (7)
#define	CAN_BTR1_SAM                                        (0x01U << CAN_BTR1_SAM_Pos)
