#define	UART_CFGR_MODE_Pos                                  (0)
#define	UART_CFGR_MODE                                      (0x03U << UART_CFGR_MODE_Pos)
#define	UART_CFGR_DFLEN_Pos                                 (2)
#define	UART_CFGR_DFLEN                                     (0x03U << UART_CFGR_DFLEN_Pos)
#define	UART_CFGR_PMOD_Pos                                  (4)
#define	UART_CFGR_PMOD                                      (0x03U << UART_CFGR_PMOD_Pos)
#define	UART_CFGR_STOP_Pos                                  (6)
#define	UART_CFGR_STOP                                      (0x01U << UART_CFGR_STOP_Pos)
#define	UART_CFGR_SWAP_Pos                                  (7)
#define	UART_CFGR_SWAP                                      (0x01U << UART_CFGR_SWAP_Pos)
#define	UART_CFGR_HDUP_Pos                                  (8)
#define	UART_CFGR_HDUP                                      (0x01U << UART_CFGR_HDUP_Pos)
#define	UART_CFGR_CKO_Pos                                   (9)
#define	UART_CFGR_CKO                                       (0x01U << UART_CFGR_CKO_Pos)
#define	UART_CFGR_ABR_Pos                                   (10)
#define	UART_CFGR_ABR                                       (0x01U << UART_CFGR_ABR_Pos)
#define	UART_CFGR_RWU_Pos                                   (11)
#define	UART_CFGR_RWU                                       (0x01U << UART_CFGR_RWU_Pos)
#define	UART_CFGR_WAKE_Pos                                  (12)
#define	UART_CFGR_WAKE                                      (0x01U << UART_CFGR_WAKE_Pos)
#define	UART_CFGR_B9POL_Pos                                 (13)
#define	UART_CFGR_B9POL                                     (0x01U << UART_CFGR_B9POL_Pos)
#define	UART_CFGR_NACK_Pos                                  (14)
#define	UART_CFGR_NACK                                      (0x01U << UART_CFGR_NACK_Pos)
#define	UART_CFGR_DIREN_Pos                                 (15)
#define	UART_CFGR_DIREN                                     (0x01U << UART_CFGR_DIREN_Pos)
#define	UART_CFGR_DIRPOL_Pos                                (16)
#define	UART_CFGR_DIRPOL                                    (0x01U << UART_CFGR_DIRPOL_Pos)
#define	UART_CFGR_BADD_Pos                                  (17)
#define	UART_CFGR_BADD                                      (0x03U << UART_CFGR_BADD_Pos)
#define	UART_CFGR_IADD_Pos                                  (19)
#define	UART_CFGR_IADD                                      (0x03U << UART_CFGR_IADD_Pos)
#define	UART_CFGR_DADD_Pos                                  (21)
#define	UART_CFGR_DADD                                      (0x03U << UART_CFGR_DADD_Pos)
#define	UART_CFGR_GTIME_Pos                                 (24)
#define	UART_CFGR_GTIME                                     (0x0FFU << UART_CFGR_GTIME_Pos)
