#define	SPI_IER_TX_Pos                                      (0)
#define	SPI_IER_TX                                          (0x01U << SPI_IER_TX_Pos)
#define	SPI_IER_RX_Pos                                      (1)
#define	SPI_IER_RX                                          (0x01U << SPI_IER_RX_Pos)
#define	SPI_IER_UNDERRUN_Pos                                (2)
#define	SPI_IER_UNDERRUN                                    (0x01U << SPI_IER_UNDERRUN_Pos)
#define	SPI_IER_RXOERR_Pos                                  (3)
#define	SPI_IER_RXOERR                                      (0x01U << SPI_IER_RXOERR_Pos)
#define	SPI_IER_RXMATCH_Pos                                 (4)
#define	SPI_IER_RXMATCH                                     (0x01U << SPI_IER_RXMATCH_Pos)
#define	SPI_IER_RXFULL_Pos                                  (5)
#define	SPI_IER_RXFULL                                      (0x01U << SPI_IER_RXFULL_Pos)
#define	SPI_IER_TXEPT_Pos                                   (6)
#define	SPI_IER_TXEPT                                       (0x01U << SPI_IER_TXEPT_Pos)
