#define	BKP_CSR_CTE_Pos                                     (0)
#define	BKP_CSR_CTE                                         (0x01U << BKP_CSR_CTE_Pos)
#define	BKP_CSR_CTI_Pos                                     (1)
#define	BKP_CSR_CTI                                         (0x01U << BKP_CSR_CTI_Pos)
#define	BKP_CSR_TPIE_Pos                                    (2)
#define	BKP_CSR_TPIE                                        (0x01U << BKP_CSR_TPIE_Pos)
#define	BKP_CSR_TEF_Pos                                     (8)
#define	BKP_CSR_TEF                                         (0x01U << BKP_CSR_TEF_Pos)
#define	BKP_CSR_TIF_Pos                                     (9)
#define	BKP_CSR_TIF                                         (0x01U << BKP_CSR_TIF_Pos)
