#define	EXTI_CR2_EXTI4_Pos                                  (3)
#define	EXTI_CR2_EXTI4                                      (0x0FU << EXTI_CR2_EXTI4_Pos)
#define	EXTI_CR2_EXTI5_Pos                                  (7)
#define	EXTI_CR2_EXTI5                                      (0x0FU << EXTI_CR2_EXTI5_Pos)
#define	EXTI_CR2_EXTI6_Pos                                  (11)
#define	EXTI_CR2_EXTI6                                      (0x0FU << EXTI_CR2_EXTI6_Pos)
#define	EXTI_CR2_EXTI7_Pos                                  (15)
#define	EXTI_CR2_EXTI7                                      (0x0FU << EXTI_CR2_EXTI7_Pos)
