#define	EXTI_CR3_EXTI8_Pos                                  (0)
#define	EXTI_CR3_EXTI8                                      (0x0FU << EXTI_CR3_EXTI8_Pos)
#define	EXTI_CR3_EXTI9_Pos                                  (4)
#define	EXTI_CR3_EXTI9                                      (0x0FU << EXTI_CR3_EXTI9_Pos)
#define	EXTI_CR3_EXTI10_Pos                                 (8)
#define	EXTI_CR3_EXTI10                                     (0x0FU << EXTI_CR3_EXTI10_Pos)
#define	EXTI_CR3_EXTI11_Pos                                 (12)
#define	EXTI_CR3_EXTI11                                     (0x0FU << EXTI_CR3_EXTI11_Pos)
