#define	EXTI_CR3_EXTI8_Pos                                  (3)
#define	EXTI_CR3_EXTI8                                      (0x0FU << EXTI_CR3_EXTI8_Pos)
#define	EXTI_CR3_EXTI9_Pos                                  (7)
#define	EXTI_CR3_EXTI9                                      (0x0FU << EXTI_CR3_EXTI9_Pos)
#define	EXTI_CR3_EXTI10_Pos                                 (11)
#define	EXTI_CR3_EXTI10                                     (0x0FU << EXTI_CR3_EXTI10_Pos)
#define	EXTI_CR3_EXTI11_Pos                                 (15)
#define	EXTI_CR3_EXTI11                                     (0x0FU << EXTI_CR3_EXTI11_Pos)
