#define	EXTI_CR4_EXTI12_Pos                                 (0)
#define	EXTI_CR4_EXTI12                                     (0x0FU << EXTI_CR4_EXTI12_Pos)
#define	EXTI_CR4_EXTI13_Pos                                 (4)
#define	EXTI_CR4_EXTI13                                     (0x0FU << EXTI_CR4_EXTI13_Pos)
#define	EXTI_CR4_EXTI14_Pos                                 (8)
#define	EXTI_CR4_EXTI14                                     (0x0FU << EXTI_CR4_EXTI14_Pos)
#define	EXTI_CR4_EXTI15_Pos                                 (12)
#define	EXTI_CR4_EXTI15                                     (0x0FU << EXTI_CR4_EXTI15_Pos)
