#define	EXTI_EMR_EMR0_Pos                                   (0)
#define	EXTI_EMR_EMR0                                       (0x01U << EXTI_EMR_EMR0_Pos)
#define	EXTI_EMR_EMR1_Pos                                   (1)
#define	EXTI_EMR_EMR1                                       (0x01U << EXTI_EMR_EMR1_Pos)
#define	EXTI_EMR_EMR2_Pos                                   (2)
#define	EXTI_EMR_EMR2                                       (0x01U << EXTI_EMR_EMR2_Pos)
#define	EXTI_EMR_EMR3_Pos                                   (3)
#define	EXTI_EMR_EMR3                                       (0x01U << EXTI_EMR_EMR3_Pos)
#define	EXTI_EMR_EMR4_Pos                                   (4)
#define	EXTI_EMR_EMR4                                       (0x01U << EXTI_EMR_EMR4_Pos)
#define	EXTI_EMR_EMR5_Pos                                   (5)
#define	EXTI_EMR_EMR5                                       (0x01U << EXTI_EMR_EMR5_Pos)
#define	EXTI_EMR_EMR6_Pos                                   (6)
#define	EXTI_EMR_EMR6                                       (0x01U << EXTI_EMR_EMR6_Pos)
#define	EXTI_EMR_EMR7_Pos                                   (7)
#define	EXTI_EMR_EMR7                                       (0x01U << EXTI_EMR_EMR7_Pos)
#define	EXTI_EMR_EMR8_Pos                                   (8)
#define	EXTI_EMR_EMR8                                       (0x01U << EXTI_EMR_EMR8_Pos)
#define	EXTI_EMR_EMR9_Pos                                   (9)
#define	EXTI_EMR_EMR9                                       (0x01U << EXTI_EMR_EMR9_Pos)
#define	EXTI_EMR_EMR10_Pos                                  (10)
#define	EXTI_EMR_EMR10                                      (0x01U << EXTI_EMR_EMR10_Pos)
#define	EXTI_EMR_EMR11_Pos                                  (11)
#define	EXTI_EMR_EMR11                                      (0x01U << EXTI_EMR_EMR11_Pos)
#define	EXTI_EMR_EMR12_Pos                                  (12)
#define	EXTI_EMR_EMR12                                      (0x01U << EXTI_EMR_EMR12_Pos)
#define	EXTI_EMR_EMR13_Pos                                  (13)
#define	EXTI_EMR_EMR13                                      (0x01U << EXTI_EMR_EMR13_Pos)
#define	EXTI_EMR_EMR14_Pos                                  (14)
#define	EXTI_EMR_EMR14                                      (0x01U << EXTI_EMR_EMR14_Pos)
#define	EXTI_EMR_EMR15_Pos                                  (15)
#define	EXTI_EMR_EMR15                                      (0x01U << EXTI_EMR_EMR15_Pos)
#define	EXTI_EMR_EMR16_Pos                                  (16)
#define	EXTI_EMR_EMR16                                      (0x01U << EXTI_EMR_EMR16_Pos)
#define	EXTI_EMR_EMR17_Pos                                  (17)
#define	EXTI_EMR_EMR17                                      (0x01U << EXTI_EMR_EMR17_Pos)
#define	EXTI_EMR_EMR18_Pos                                  (18)
#define	EXTI_EMR_EMR18                                      (0x01U << EXTI_EMR_EMR18_Pos)
