#define	EXTI_FTSR_TR0_Pos                                   (0)
#define	EXTI_FTSR_TR0                                       (0x01U << EXTI_FTSR_TR0_Pos)
#define	EXTI_FTSR_TR1_Pos                                   (1)
#define	EXTI_FTSR_TR1                                       (0x01U << EXTI_FTSR_TR1_Pos)
#define	EXTI_FTSR_TR2_Pos                                   (2)
#define	EXTI_FTSR_TR2                                       (0x01U << EXTI_FTSR_TR2_Pos)
#define	EXTI_FTSR_TR3_Pos                                   (3)
#define	EXTI_FTSR_TR3                                       (0x01U << EXTI_FTSR_TR3_Pos)
#define	EXTI_FTSR_TR4_Pos                                   (4)
#define	EXTI_FTSR_TR4                                       (0x01U << EXTI_FTSR_TR4_Pos)
#define	EXTI_FTSR_TR5_Pos                                   (5)
#define	EXTI_FTSR_TR5                                       (0x01U << EXTI_FTSR_TR5_Pos)
#define	EXTI_FTSR_TR6_Pos                                   (6)
#define	EXTI_FTSR_TR6                                       (0x01U << EXTI_FTSR_TR6_Pos)
#define	EXTI_FTSR_TR7_Pos                                   (7)
#define	EXTI_FTSR_TR7                                       (0x01U << EXTI_FTSR_TR7_Pos)
#define	EXTI_FTSR_TR8_Pos                                   (8)
#define	EXTI_FTSR_TR8                                       (0x01U << EXTI_FTSR_TR8_Pos)
#define	EXTI_FTSR_TR9_Pos                                   (9)
#define	EXTI_FTSR_TR9                                       (0x01U << EXTI_FTSR_TR9_Pos)
#define	EXTI_FTSR_TR10_Pos                                  (10)
#define	EXTI_FTSR_TR10                                      (0x01U << EXTI_FTSR_TR10_Pos)
#define	EXTI_FTSR_TR11_Pos                                  (11)
#define	EXTI_FTSR_TR11                                      (0x01U << EXTI_FTSR_TR11_Pos)
#define	EXTI_FTSR_TR12_Pos                                  (12)
#define	EXTI_FTSR_TR12                                      (0x01U << EXTI_FTSR_TR12_Pos)
#define	EXTI_FTSR_TR13_Pos                                  (13)
#define	EXTI_FTSR_TR13                                      (0x01U << EXTI_FTSR_TR13_Pos)
#define	EXTI_FTSR_TR14_Pos                                  (14)
#define	EXTI_FTSR_TR14                                      (0x01U << EXTI_FTSR_TR14_Pos)
#define	EXTI_FTSR_TR15_Pos                                  (15)
#define	EXTI_FTSR_TR15                                      (0x01U << EXTI_FTSR_TR15_Pos)
#define	EXTI_FTSR_TR16_Pos                                  (16)
#define	EXTI_FTSR_TR16                                      (0x01U << EXTI_FTSR_TR16_Pos)
#define	EXTI_FTSR_TR17_Pos                                  (17)
#define	EXTI_FTSR_TR17                                      (0x01U << EXTI_FTSR_TR17_Pos)
#define	EXTI_FTSR_TR18_Pos                                  (18)
#define	EXTI_FTSR_TR18                                      (0x01U << EXTI_FTSR_TR18_Pos)
