#define	GPIO_CRH_MODE8_Pos                                  (0)
#define	GPIO_CRH_MODE8                                      (0x03U << GPIO_CRH_MODE8_Pos)
#define	GPIO_CRH_CNF8_Pos                                   (2)
#define	GPIO_CRH_CNF8                                       (0x03U << GPIO_CRH_CNF8_Pos)
#define	GPIO_CRH_MODE9_Pos                                  (4)
#define	GPIO_CRH_MODE9                                      (0x03U << GPIO_CRH_MODE9_Pos)
#define	GPIO_CRH_CNF9_Pos                                   (6)
#define	GPIO_CRH_CNF9                                       (0x03U << GPIO_CRH_CNF9_Pos)
#define	GPIO_CRH_MODE10_Pos                                 (8)
#define	GPIO_CRH_MODE10                                     (0x03U << GPIO_CRH_MODE10_Pos)
#define	GPIO_CRH_CNF10_Pos                                  (10)
#define	GPIO_CRH_CNF10                                      (0x03U << GPIO_CRH_CNF10_Pos)
#define	GPIO_CRH_MODE11_Pos                                 (12)
#define	GPIO_CRH_MODE11                                     (0x03U << GPIO_CRH_MODE11_Pos)
#define	GPIO_CRH_CNF11_Pos                                  (14)
#define	GPIO_CRH_CNF11                                      (0x03U << GPIO_CRH_CNF11_Pos)
#define	GPIO_CRH_MODE12_Pos                                 (16)
#define	GPIO_CRH_MODE12                                     (0x03U << GPIO_CRH_MODE12_Pos)
#define	GPIO_CRH_CNF12_Pos                                  (18)
#define	GPIO_CRH_CNF12                                      (0x03U << GPIO_CRH_CNF12_Pos)
#define	GPIO_CRH_MODE13_Pos                                 (20)
#define	GPIO_CRH_MODE13                                     (0x03U << GPIO_CRH_MODE13_Pos)
#define	GPIO_CRH_CNF13_Pos                                  (22)
#define	GPIO_CRH_CNF13                                      (0x03U << GPIO_CRH_CNF13_Pos)
#define	GPIO_CRH_MODE14_Pos                                 (24)
#define	GPIO_CRH_MODE14                                     (0x03U << GPIO_CRH_MODE14_Pos)
#define	GPIO_CRH_CNF14_Pos                                  (26)
#define	GPIO_CRH_CNF14                                      (0x03U << GPIO_CRH_CNF14_Pos)
#define	GPIO_CRH_MODE15_Pos                                 (28)
#define	GPIO_CRH_MODE15                                     (0x03U << GPIO_CRH_MODE15_Pos)
#define	GPIO_CRH_CNF15_Pos                                  (30)
#define	GPIO_CRH_CNF15                                      (0x03U << GPIO_CRH_CNF15_Pos)
