#define	GPIO_CRL_MODE0_Pos                                  (0)
#define	GPIO_CRL_MODE0                                      (0x03U << GPIO_CRL_MODE0_Pos)
#define	GPIO_CRL_CNF0_Pos                                   (2)
#define	GPIO_CRL_CNF0                                       (0x03U << GPIO_CRL_CNF0_Pos)
#define	GPIO_CRL_MODE1_Pos                                  (4)
#define	GPIO_CRL_MODE1                                      (0x03U << GPIO_CRL_MODE1_Pos)
#define	GPIO_CRL_CNF1_Pos                                   (6)
#define	GPIO_CRL_CNF1                                       (0x03U << GPIO_CRL_CNF1_Pos)
#define	GPIO_CRL_MODE2_Pos                                  (8)
#define	GPIO_CRL_MODE2                                      (0x03U << GPIO_CRL_MODE2_Pos)
#define	GPIO_CRL_CNF2_Pos                                   (10)
#define	GPIO_CRL_CNF2                                       (0x03U << GPIO_CRL_CNF2_Pos)
#define	GPIO_CRL_MODE3_Pos                                  (12)
#define	GPIO_CRL_MODE3                                      (0x03U << GPIO_CRL_MODE3_Pos)
#define	GPIO_CRL_CNF3_Pos                                   (14)
#define	GPIO_CRL_CNF3                                       (0x03U << GPIO_CRL_CNF3_Pos)
#define	GPIO_CRL_MODE4_Pos                                  (16)
#define	GPIO_CRL_MODE4                                      (0x03U << GPIO_CRL_MODE4_Pos)
#define	GPIO_CRL_CNF4_Pos                                   (18)
#define	GPIO_CRL_CNF4                                       (0x03U << GPIO_CRL_CNF4_Pos)
#define	GPIO_CRL_MODE5_Pos                                  (20)
#define	GPIO_CRL_MODE5                                      (0x03U << GPIO_CRL_MODE5_Pos)
#define	GPIO_CRL_CNF5_Pos                                   (22)
#define	GPIO_CRL_CNF5                                       (0x03U << GPIO_CRL_CNF5_Pos)
#define	GPIO_CRL_MODE6_Pos                                  (24)
#define	GPIO_CRL_MODE6                                      (0x03U << GPIO_CRL_MODE6_Pos)
#define	GPIO_CRL_CNF6_Pos                                   (26)
#define	GPIO_CRL_CNF6                                       (0x03U << GPIO_CRL_CNF6_Pos)
#define	GPIO_CRL_MODE7_Pos                                  (28)
#define	GPIO_CRL_MODE7                                      (0x03U << GPIO_CRL_MODE7_Pos)
#define	GPIO_CRL_CNF7_Pos                                   (30)
#define	GPIO_CRL_CNF7                                       (0x03U << GPIO_CRL_CNF7_Pos)
