#define	GPIO_EXTICR0_EXTI0_Pos                              (0)
#define	GPIO_EXTICR0_EXTI0                                  (0x0FU << GPIO_EXTICR0_EXTI0_Pos)
#define	GPIO_EXTICR0_EXTI1_Pos                              (4)
#define	GPIO_EXTICR0_EXTI1                                  (0x0FU << GPIO_EXTICR0_EXTI1_Pos)
#define	GPIO_EXTICR0_EXTI2_Pos                              (8)
#define	GPIO_EXTICR0_EXTI2                                  (0x0FU << GPIO_EXTICR0_EXTI2_Pos)
#define	GPIO_EXTICR0_EXTI3_Pos                              (12)
#define	GPIO_EXTICR0_EXTI3                                  (0x0FU << GPIO_EXTICR0_EXTI3_Pos)
