#define	GPIO_EXTICR2_EXTI8_Pos                              (0)
#define	GPIO_EXTICR2_EXTI8                                  (0x0FU << GPIO_EXTICR2_EXTI8_Pos)
#define	GPIO_EXTICR2_EXTI9_Pos                              (4)
#define	GPIO_EXTICR2_EXTI9                                  (0x0FU << GPIO_EXTICR2_EXTI9_Pos)
#define	GPIO_EXTICR2_EXTI10_Pos                             (8)
#define	GPIO_EXTICR2_EXTI10                                 (0x0FU << GPIO_EXTICR2_EXTI10_Pos)
#define	GPIO_EXTICR2_EXTI11_Pos                             (12)
#define	GPIO_EXTICR2_EXTI11                                 (0x0FU << GPIO_EXTICR2_EXTI11_Pos)
