#define	GPIO_EXTICR2_EXTI8_Pos                              (3)
#define	GPIO_EXTICR2_EXTI8                                  (0x0FU << GPIO_EXTICR2_EXTI8_Pos)
#define	GPIO_EXTICR2_EXTI9_Pos                              (7)
#define	GPIO_EXTICR2_EXTI9                                  (0x0FU << GPIO_EXTICR2_EXTI9_Pos)
#define	GPIO_EXTICR2_EXTI10_Pos                             (11)
#define	GPIO_EXTICR2_EXTI10                                 (0x0FU << GPIO_EXTICR2_EXTI10_Pos)
#define	GPIO_EXTICR2_EXTI11_Pos                             (15)
#define	GPIO_EXTICR2_EXTI11                                 (0x0FU << GPIO_EXTICR2_EXTI11_Pos)
