#define	GPIO_EXTICR4_EXTI12_Pos                             (0)
#define	GPIO_EXTICR4_EXTI12                                 (0x0FU << GPIO_EXTICR4_EXTI12_Pos)
#define	GPIO_EXTICR4_EXTI13_Pos                             (4)
#define	GPIO_EXTICR4_EXTI13                                 (0x0FU << GPIO_EXTICR4_EXTI13_Pos)
#define	GPIO_EXTICR4_EXTI14_Pos                             (8)
#define	GPIO_EXTICR4_EXTI14                                 (0x0FU << GPIO_EXTICR4_EXTI14_Pos)
#define	GPIO_EXTICR4_EXTI15_Pos                             (12)
#define	GPIO_EXTICR4_EXTI15                                 (0x0FU << GPIO_EXTICR4_EXTI15_Pos)
