#define	GPIO_MAPR_SPI1_REMAP_Pos                            (0)
#define	GPIO_MAPR_SPI1_REMAP                                (0x01U << GPIO_MAPR_SPI1_REMAP_Pos)
#define	GPIO_MAPR_I2C1_REMAP_Pos                            (1)
#define	GPIO_MAPR_I2C1_REMAP                                (0x01U << GPIO_MAPR_I2C1_REMAP_Pos)
#define	GPIO_MAPR_UART1_REMAP_Pos                           (2)
#define	GPIO_MAPR_UART1_REMAP                               (0x01U << GPIO_MAPR_UART1_REMAP_Pos)
#define	GPIO_MAPR_UART3_REMAP_Pos                           (4)
#define	GPIO_MAPR_UART3_REMAP                               (0x03U << GPIO_MAPR_UART3_REMAP_Pos)
#define	GPIO_MAPR_TIM1_REMAP_Pos                            (6)
#define	GPIO_MAPR_TIM1_REMAP                                (0x03U << GPIO_MAPR_TIM1_REMAP_Pos)
#define	GPIO_MAPR_TIM2_REMAP_Pos                            (8)
#define	GPIO_MAPR_TIM2_REMAP                                (0x03U << GPIO_MAPR_TIM2_REMAP_Pos)
#define	GPIO_MAPR_TIM3_REMAP_Pos                            (10)
#define	GPIO_MAPR_TIM3_REMAP                                (0x03U << GPIO_MAPR_TIM3_REMAP_Pos)
#define	GPIO_MAPR_CAN_REMAP_Pos                             (13)
#define	GPIO_MAPR_CAN_REMAP                                 (0x03U << GPIO_MAPR_CAN_REMAP_Pos)
#define	GPIO_MAPR_PD01_REMAP_Pos                            (15)
#define	GPIO_MAPR_PD01_REMAP                                (0x01U << GPIO_MAPR_PD01_REMAP_Pos)
#define	GPIO_MAPR_SWJ_CFG_Pos                               (24)
#define	GPIO_MAPR_SWJ_CFG                                   (0x07U << GPIO_MAPR_SWJ_CFG_Pos)
