#define	SPI_CFGR_MODE_Pos                                   (0)
#define	SPI_CFGR_MODE                                       (0x01U << SPI_CFGR_MODE_Pos)
#define	SPI_CFGR_CPSEL_Pos                                  (1)
#define	SPI_CFGR_CPSEL                                      (0x03U << SPI_CFGR_CPSEL_Pos)
#define	SPI_CFGR_LSB_Pos                                    (3)
#define	SPI_CFGR_LSB                                        (0x01U << SPI_CFGR_LSB_Pos)
#define	SPI_CFGR_NSS_Pos                                    (4)
#define	SPI_CFGR_NSS                                        (0x01U << SPI_CFGR_NSS_Pos)
#define	SPI_CFGR_NSSA_Pos                                   (5)
#define	SPI_CFGR_NSSA                                       (0x07U << SPI_CFGR_NSSA_Pos)
#define	SPI_CFGR_FGAP_Pos                                   (8)
#define	SPI_CFGR_FGAP                                       (0x07U << SPI_CFGR_FGAP_Pos)
#define	SPI_CFGR_WIDTH_Pos                                  (11)
#define	SPI_CFGR_WIDTH                                      (0x0FU << SPI_CFGR_WIDTH_Pos)
#define	SPI_CFGR_CNT_Pos                                    (15)
#define	SPI_CFGR_CNT                                        (0x01FFU << SPI_CFGR_CNT_Pos)
