#define	SPI_IER_TXE_Pos                                     (0)
#define	SPI_IER_TXE                                         (0x01U << SPI_IER_TXE_Pos)
#define	SPI_IER_TXC_Pos                                     (1)
#define	SPI_IER_TXC                                         (0x01U << SPI_IER_TXC_Pos)
#define	SPI_IER_RXNE_Pos                                    (2)
#define	SPI_IER_RXNE                                        (0x01U << SPI_IER_RXNE_Pos)
#define	SPI_IER_OVER_Pos                                    (3)
#define	SPI_IER_OVER                                        (0x01U << SPI_IER_OVER_Pos)
#define	SPI_IER_TUDR_Pos                                    (4)
#define	SPI_IER_TUDR                                        (0x01U << SPI_IER_TUDR_Pos)
#define	SPI_IER_RMAH_Pos                                    (5)
#define	SPI_IER_RMAH                                        (0x01U << SPI_IER_RMAH_Pos)
